FROM python:3.12-slim 

RUN apt-get update && apt-get install -y \
    build-essential \
    iputils-ping \
    iproute2 \
    dos2unix && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY ./client /app

RUN pip install --upgrade pip
RUN pip install streamlit==1.29.0
RUN pip install streamlit_autorefresh
RUN dos2unix /app/startup.sh
RUN chmod +x /app/startup.sh

EXPOSE 8501

CMD ["sh", "-c", "/app/startup.sh && tail -f /dev/null"]
