version: '3.8'

services:
  server:
    build: .
    container_name: spark-chat-server
    networks:
      spark-net:
        ipv4_address: 192.168.1.100
    ports:
      - "12345:12345"
    
  client:
    build: .
    container_name: spark-chat-client
    stdin_open: true
    tty: true
    networks:
      spark-net:
        ipv4_address: 192.168.1.101
    entrypoint: ["python", "client/client.py", "192.168.1.100"]
    depends_on:
      - server

networks:
  spark-net:
    driver: bridge
