FROM python:3.12-slim

RUN apt-get update && apt-get install -y \
    build-essential \
    iputils-ping \
    iproute2 && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY ./server /app
RUN chmod +x ./startup.sh

CMD ["sh", "-c", "/app/startup.sh & python3 server.py main & wait"]
